- name: install cart component 
  hosts: cart
  become: yes 

  tasks: 
  - name: setup the repo
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: install nodejs
    ansible.builtin.yum:
     name: nodejs
     state: installed

  - name: check user roboshop exist or not
    ansible.builtin.command: id roboshop
    register: srikar
    ignore_errors: true
    
  - name: create the user
    ansible.builtin.user: 
     name: roboshop
    when: srikar.rc != 0

  - name: check app directory exist or not
    ansible.builtin.stat:
     path: /app
     register: srikar
    
  - name: create app directory 
    ansible.builtin.file:
     path: /app
     state: directory 
    when: srikar.stat.exists == false

  - name: download and unzip
    ansible.builtin.unarchive:
     src: https://roboshop-builds.s3.amazonaws.com/cart.zip
     dest: /app
     remote_src: yes 

  - name: install dependencies
    ansible.builtin.command: npm install
    args: 
     chdir: /app

  - name: copy cart.service
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service

  - name: daemon reload
    ansible.builtin.systemd: 
     daemon_reload: true
  
  - name: enable and start the cart
    ansible.builtin.service:
     name: cart
     state: started
     enabled: yes 

